<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="author" content="Lucas Fernandes de Magalhães" />
  <title>Condenados pela ideologia?</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/reveal.js-3.3.0.1/css/reveal.css"/>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="index_files/reveal.js-3.3.0.1/css/theme/simple.css" id="theme">


  <!-- some tweaks to reveal css -->
  <style type="text/css">
    .reveal h1 { font-size: 2.0em; }
    .reveal h2 { font-size: 1.5em;  }
    .reveal h3 { font-size: 1.25em;	}
    .reveal h4 { font-size: 1em;	}

    .reveal .slides>section,
    .reveal .slides>section>section {
      padding: 0px 0px;
    }



    .reveal table {
      border-width: 1px;
      border-spacing: 2px;
      border-style: dotted;
      border-color: gray;
      border-collapse: collapse;
      font-size: 0.7em;
    }

    .reveal table th {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      font-weight: bold;
      border-style: dotted;
      border-color: gray;
    }

    .reveal table td {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      border-style: dotted;
      border-color: gray;
    }


  </style>

    <style type="text/css">code{white-space: pre;}</style>

    <link rel="stylesheet" href="styles.css"/>

<!-- Printing and PDF exports -->
<script id="paper-css" type="application/dynamic-css">

/* Default Print Stylesheet Template
   by Rob Glazebrook of CSSnewbie.com
   Last Updated: June 4, 2008

   Feel free (nay, compelled) to edit, append, and
   manipulate this file as you see fit. */


@media print {

	/* SECTION 1: Set default width, margin, float, and
	   background. This prevents elements from extending
	   beyond the edge of the printed page, and prevents
	   unnecessary background images from printing */
	html {
		background: #fff;
		width: auto;
		height: auto;
		overflow: visible;
	}
	body {
		background: #fff;
		font-size: 20pt;
		width: auto;
		height: auto;
		border: 0;
		margin: 0 5%;
		padding: 0;
		overflow: visible;
		float: none !important;
	}

	/* SECTION 2: Remove any elements not needed in print.
	   This would include navigation, ads, sidebars, etc. */
	.nestedarrow,
	.controls,
	.fork-reveal,
	.share-reveal,
	.state-background,
	.reveal .progress,
	.reveal .backgrounds {
		display: none !important;
	}

	/* SECTION 3: Set body font face, size, and color.
	   Consider using a serif font for readability. */
	body, p, td, li, div {
		font-size: 20pt!important;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		color: #000;
	}

	/* SECTION 4: Set heading font face, sizes, and color.
	   Differentiate your headings from your body text.
	   Perhaps use a large sans-serif for distinction. */
	h1,h2,h3,h4,h5,h6 {
		color: #000!important;
		height: auto;
		line-height: normal;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		text-shadow: 0 0 0 #000 !important;
		text-align: left;
		letter-spacing: normal;
	}
	/* Need to reduce the size of the fonts for printing */
	h1 { font-size: 28pt !important;  }
	h2 { font-size: 24pt !important; }
	h3 { font-size: 22pt !important; }
	h4 { font-size: 22pt !important; font-variant: small-caps; }
	h5 { font-size: 21pt !important; }
	h6 { font-size: 20pt !important; font-style: italic; }

	/* SECTION 5: Make hyperlinks more usable.
	   Ensure links are underlined, and consider appending
	   the URL to the end of the link for usability. */
	a:link,
	a:visited {
		color: #000 !important;
		font-weight: bold;
		text-decoration: underline;
	}
	/*
	.reveal a:link:after,
	.reveal a:visited:after {
		content: " (" attr(href) ") ";
		color: #222 !important;
		font-size: 90%;
	}
	*/


	/* SECTION 6: more reveal.js specific additions by @skypanther */
	ul, ol, div, p {
		visibility: visible;
		position: static;
		width: auto;
		height: auto;
		display: block;
		overflow: visible;
		margin: 0;
		text-align: left !important;
	}
	.reveal pre,
	.reveal table {
		margin-left: 0;
		margin-right: 0;
	}
	.reveal pre code {
		padding: 20px;
		border: 1px solid #ddd;
	}
	.reveal blockquote {
		margin: 20px 0;
	}
	.reveal .slides {
		position: static !important;
		width: auto !important;
		height: auto !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 0 !important;
		zoom: 1 !important;

		overflow: visible !important;
		display: block !important;

		text-align: left !important;
		-webkit-perspective: none;
		   -moz-perspective: none;
		    -ms-perspective: none;
		        perspective: none;

		-webkit-perspective-origin: 50% 50%;
		   -moz-perspective-origin: 50% 50%;
		    -ms-perspective-origin: 50% 50%;
		        perspective-origin: 50% 50%;
	}
	.reveal .slides section {
		visibility: visible !important;
		position: static !important;
		width: auto !important;
		height: auto !important;
		display: block !important;
		overflow: visible !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 60px 20px !important;
		z-index: auto !important;

		opacity: 1 !important;

		page-break-after: always !important;

		-webkit-transform-style: flat !important;
		   -moz-transform-style: flat !important;
		    -ms-transform-style: flat !important;
		        transform-style: flat !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;

		-webkit-transition: none !important;
		   -moz-transition: none !important;
		    -ms-transition: none !important;
		        transition: none !important;
	}
	.reveal .slides section.stack {
		padding: 0 !important;
	}
	.reveal section:last-of-type {
		page-break-after: avoid !important;
	}
	.reveal section .fragment {
		opacity: 1 !important;
		visibility: visible !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;
	}
	.reveal section img {
		display: block;
		margin: 15px 0px;
		background: rgba(255,255,255,1);
		border: 1px solid #666;
		box-shadow: none;
	}

	.reveal section small {
		font-size: 0.8em;
	}

}  
</script>


<script id="pdf-css" type="application/dynamic-css">
    
/**
 * This stylesheet is used to print reveal.js
 * presentations to PDF.
 *
 * https://github.com/hakimel/reveal.js#pdf-export
 */

* {
	-webkit-print-color-adjust: exact;
}

body {
	margin: 0 auto !important;
	border: 0;
	padding: 0;
	float: none !important;
	overflow: visible;
}

html {
	width: 100%;
	height: 100%;
	overflow: visible;
}

/* Remove any elements not needed in print. */
.nestedarrow,
.reveal .controls,
.reveal .progress,
.reveal .playback,
.reveal.overview,
.fork-reveal,
.share-reveal,
.state-background {
	display: none !important;
}

h1, h2, h3, h4, h5, h6 {
	text-shadow: 0 0 0 #000 !important;
}

.reveal pre code {
	overflow: hidden !important;
	font-family: Courier, 'Courier New', monospace !important;
}

ul, ol, div, p {
	visibility: visible;
	position: static;
	width: auto;
	height: auto;
	display: block;
	overflow: visible;
	margin: auto;
}
.reveal {
	width: auto !important;
	height: auto !important;
	overflow: hidden !important;
}
.reveal .slides {
	position: static;
	width: 100%;
	height: auto;

	left: auto;
	top: auto;
	margin: 0 !important;
	padding: 0 !important;

	overflow: visible;
	display: block;

	-webkit-perspective: none;
	   -moz-perspective: none;
	    -ms-perspective: none;
	        perspective: none;

	-webkit-perspective-origin: 50% 50%; /* there isn't a none/auto value but 50-50 is the default */
	   -moz-perspective-origin: 50% 50%;
	    -ms-perspective-origin: 50% 50%;
	        perspective-origin: 50% 50%;
}

.reveal .slides section {
	page-break-after: always !important;

	visibility: visible !important;
	position: relative !important;
	display: block !important;
	position: relative !important;

	margin: 0 !important;
	padding: 0 !important;
	box-sizing: border-box !important;
	min-height: 1px;

	opacity: 1 !important;

	-webkit-transform-style: flat !important;
	   -moz-transform-style: flat !important;
	    -ms-transform-style: flat !important;
	        transform-style: flat !important;

	-webkit-transform: none !important;
	   -moz-transform: none !important;
	    -ms-transform: none !important;
	        transform: none !important;
}

.reveal section.stack {
	margin: 0 !important;
	padding: 0 !important;
	page-break-after: avoid !important;
	height: auto !important;
	min-height: auto !important;
}

.reveal img {
	box-shadow: none;
}

.reveal .roll {
	overflow: visible;
	line-height: 1em;
}

/* Slide backgrounds are placed inside of their slide when exporting to PDF */
.reveal section .slide-background {
	display: block !important;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	z-index: -1;
}

/* All elements should be above the slide-background */
.reveal section>* {
	position: relative;
	z-index: 1;
}

/* Display slide speaker notes when 'showNotes' is enabled */
.reveal .speaker-notes-pdf {
	display: block;
	width: 100%;
	max-height: none;
	left: auto;
	top: auto;
	z-index: 100;
}

/* Display slide numbers when 'slideNumber' is enabled */
.reveal .slide-number-pdf {
	display: block;
	position: absolute;
	font-size: 14px;
}

</script>


<script>
var style = document.createElement( 'style' );
style.type = 'text/css';
var style_script_id = window.location.search.match( /print-pdf/gi ) ? 'pdf-css' : 'paper-css';
var style_script = document.getElementById(style_script_id).text;
style.innerHTML = style_script;
document.getElementsByTagName('head')[0].appendChild(style);
</script>

    <script src="index_files/kePrint-0.0.1/kePrint.js"></script>
</head>
<body>
  <div class="reveal">
    <div class="slides">

<section>
    <h1 class="title">Condenados pela ideologia?</h1>
  <h1 class="subtitle">Uma análise das sentenças criminais do TJSP</h1>
    <h2 class="author">Lucas Fernandes de Magalhães</h2>
</section>

<section><section id="introducao" class="title-slide slide level1"><h1>Introdução</h1></section><section id="objetivo" class="slide level2">
<h2>Objetivo</h2>
<p>   </p>
<ul>
<li>Explicar porque os juízes decidem da forma como decidem.</li>
</ul>
<p>   </p>
<ul>
<li>Mais especificamente, explicar porque os juízes decidem de forma diversa casos semelhantes.</li>
</ul>
</section><section id="duas-situacoes-quatro-decisoes" class="slide level2">
<h2>Duas situações, quatro decisões</h2>
<p>   </p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Caso
</th>
<th style="text-align:left;">
Decisão
</th>
</tr>
</thead>
<tbody>
<tr grouplength="2">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Situação 1</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left: 2em;" indentlevel="1">
Acusado de tráfico. Segundo policiais, o acusado jogou uma sacola no chão contendo drogas às 18hrs. O réu negou e apresentou provas de que havia trabalhado como ajudante de pedreiro até às 17hrs.
</td>
<td style="text-align:left;">
Condenação
</td>
</tr>
<tr>
<td style="text-align:left; padding-left: 2em;" indentlevel="1">
Acusada de tráfico. Segundo policiais, a ré jogou um embrulho no chão contendo drogas. A ré negou e disse que estava apenas no lugar ‘errado, na hora errada’.
</td>
<td style="text-align:left;">
Absolvição
</td>
</tr>
<tr grouplength="2">
<td colspan="2" style="border-bottom: 1px solid;">
<strong>Situação 2</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left: 2em;" indentlevel="1">
Acusado de furto. Furtou cinco cuecas no valor de R$ 41,95.
</td>
<td style="text-align:left;">
Condenação
</td>
</tr>
<tr>
<td style="text-align:left; padding-left: 2em;" indentlevel="1">
Acusado de furto. Furtou uma furadeira elétrica no valor de R$ 252,90
</td>
<td style="text-align:left;">
Absolvição
</td>
</tr>
</tbody>
</table>
</section><section id="justificativa-em-tres-niveis" class="slide level2">
<h2>Justificativa em três níveis</h2>
<p>   </p>
<ul>
<li>Por que estudar o comportamento de juízes?</li>
</ul>
<p>   </p>
<ul>
<li>Por que estudar Juízes de 1º Grau?</li>
</ul>
<p>   </p>
<ul>
<li>Por que estudar sentenças criminais?</li>
</ul>
</section></section>
<section><section id="explicando-o-comportamento-judicial" class="title-slide slide level1"><h1>Explicando o comportamento judicial</h1></section><section id="teorias" class="slide level2">
<h2>Teorias</h2>
<p>   </p>
<ul>
<li>Teoria Legal?</li>
</ul>
<p>   </p>
<ul>
<li>Teoria Atitudinal</li>
</ul>
<p>   </p>
<ul>
<li>Teoria Estratégica</li>
</ul>
</section><section id="o-que-sao-preferencias-politicas" class="slide level2">
<h2>O que são preferências políticas</h2>
<p>   </p>
<center>
<img data-src="graf1.PNG" />
</center>
</section><section id="dimensao-da-politica-criminal-garantismo-punitivismo" class="slide level2">
<h2>Dimensão da política criminal: garantismo-punitivismo</h2>
<p>   </p>
<center>
<img data-src="ideologia.PNG" />
</center>
</section><section id="teoria-atitudinal" class="slide level2">
<h2>Teoria Atitudinal</h2>
<p>   </p>
<center>
<img data-src="atitudinal.PNG" />
</center>
</section><section id="teoria-estrategica" class="slide level2">
<h2>Teoria Estratégica</h2>
<p>   </p>
<ul>
<li><strong>Objetivos</strong></li>
</ul>
<p>   </p>
<ul>
<li><strong>Antecipação</strong></li>
</ul>
<p>   </p>
<ul>
<li><strong>Contexto institucional</strong></li>
</ul>
</section><section id="teoria-estrategica-1" class="slide level2">
<h2>Teoria Estratégica</h2>
<p>   </p>
<center>
<img data-src="atitudinal.PNG" />
</center>
</section><section id="explicacoes-distintas-predicoes-iguais" class="slide level2">
<h2>Explicações distintas, predições iguais</h2>
<p>   </p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Teorias
</th>
<th style="text-align:left;">
Incentivos.relevantes
</th>
<th style="text-align:left;">
Comportamento.Predito
</th>
<th style="text-align:left;">
Explicação
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="2">
Atitudinal
</td>
<td style="text-align:left;">
Sim
</td>
<td style="text-align:left;">
Sincero
</td>
<td style="text-align:left;">
Ativação das preferências políticas
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Não
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Sincero
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Ativação das preferências políticas
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="2">
Estratégica
</td>
<td style="text-align:left;">
Sim
</td>
<td style="text-align:left;">
Sofisticado
</td>
<td style="text-align:left;">
Maximização dos objetivos
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Não
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Sincero
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Ausência de incentivos relevantes
</td>
</tr>
</tbody>
</table>
</section><section id="explicando-o-comportamento-dos-juizes-do-tjsp" class="slide level2">
<h2>Explicando o comportamento dos juízes do TJSP</h2>
<p>   </p>
<p><strong>Teoria Atitudinal</strong> - Os juízes decidem de acordo com suas preferências políticas.    </p>
<p><strong>Teoria Estratégica</strong> - Os juízes decidem de acordo com suas preferências políticas:</p>
<ul>
<li>Julgamento Individual (Contexto colegiado)</li>
<li>Decisão não passível de revisão pelos demais Poderes (Contexto da separação entre os poderes)</li>
<li>Distribuição aleatória dos recursos (Contexto hierárquico)</li>
<li>Falta de homogeneidade nos Tribunais (Contexto Hierárquico)</li>
</ul>
</section><section id="modelo-e-hipotese" class="slide level2">
<h2>Modelo e hipótese</h2>
<p>   </p>
<center>
<span class="math display">\[\underbrace{d_{ic}}_\text{Decisão do juiz i no caso c} = \alpha + \underbrace{\beta_1I_i}_\text{Ideologia do juiz i} + \underbrace{\epsilon}_\text{Erro normalmente distribuído}\]</span>
</center>
<p>   </p>
<p><strong>Hipótese</strong>: Juízes punitivistas possuem uma maior probabilidade de proferirem uma sentença condenatória do que juízes garantistas</p>
</section></section>
<section><section id="mensurando-as-preferencias-politicas" class="title-slide slide level1"><h1>Mensurando as preferências políticas</h1></section><section id="duas-estrategias" class="slide level2">
<h2>Duas estratégias</h2>
<p>   </p>
<p>A preferência política é uma variável latente, isto é, não é passível de ser mensurada diretamente, diferente da altura, sexo ou peso, por exemplo. Em razão disso, para medi-la necessitamos de alternativas indiretas como:</p>
<p>   </p>
<ul>
<li>Proxy</li>
</ul>
<p>   </p>
<ul>
<li>Comportamento observado</li>
</ul>
</section><section id="proxy" class="slide level2">
<h2>Proxy</h2>
<p>   </p>
<center>
<img data-src="proxy.PNG" />
</center>
</section><section id="comportamento-observado" class="slide level2">
<h2>Comportamento observado</h2>
<p>   </p>
<center>
<img data-src="comportamento.PNG" />
</center>
</section><section id="estrategia-adotada" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<p>Se a decisão judicial é afetada pela preferência polítia do juiz, isso significa que ele apenas decidiria pela absolvição se, e somente se, a média entre a absolvição e a condenação fosse maior do que seu ponto ideal. Inversamente, um juiz condenaria se, e somente se, a média entre a absolvição e a condenação fosse menor do que seu ponto ideal.</p>
<p>   </p>
<p>Para facilitar, a média entre a absolvição e a condenação será denominada “ponto de corte” do caso sob julgamento. Assim, um ponto ideal superior e outro inferior ao ponto de corte implica uma decisão condenatória e uma decisão absolutória, respectivamente.</p>
</section><section id="estrategia-adotada-1" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<center>
<img data-src="estrategia1.PNG" />
</center>
</section><section id="estrategia-adotada-2" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<center>
<img data-src="estrategia2.PNG" />
</center>
</section><section id="estrategia-adotada-3" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<center>
<img data-src="estrategia3.PNG" />
</center>
</section><section id="estrategia-adotada-4" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<p><strong>Solução</strong></p>
<p>Calcular a proporção de sentenças condenatórias dos juízes em cada crime. Como os processos são distribuídos aleatoriamente, com um tamanho de amostra razoável, as diferenças de caso para caso se tornam irrelevantes.</p>
<p>   </p>
<p>Dessa maneira, a proporção de decisões de condenação serve como uma boa estimativa do ponto ideal do juiz na dimensão política garantismo-punitivismo: quanto maior a proporção de condenação, mais punitivista será o juiz; quanto menor a proporção de condenação, mais garantista ele será.</p>
</section><section id="estrategia-adotada-5" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<p>Juízes não julgam apenas um tipo de crime, e sim vários. Assim, podemos obter a proporção de decisões condenatórias de um juiz em uma série de crimes. Saber as proporções de decisões condenatórias dos juízes em vários crimes nos permite estimar os seus pontos ideais com ainda maior precisão.</p>
<p>   </p>
<p>Podemos calcular os pontos ideais dos juízes a partir das proporções de condenações em uma série de crimes usando a fórmula da distância euclidiana:</p>
<p>   </p>
<p><span class="math display">\[d(a,b)=\sqrt{\sum_{i=1}^{n}(a_i - b_i)^2} \]</span></p>
</section><section id="estrategia-adotada-6" class="slide level2">
<h2>Estratégia adotada</h2>
<p>   </p>
<p>O cálculo das as distâncias euclidianas entre os juízes retorna uma matriz de distância.</p>
<p>   </p>
<p>Como o nosso objetivo é obter um vetor (que será a variável preferência política) e não uma matriz, iremos selecionar o juiz mais garantista como sendo a referência (ou o âncora) e calcularemos todas as distâncias a partir dele.</p>
</section><section id="estrategia-adotada---exemplo" class="slide level2">
<h2>Estratégia adotada - exemplo</h2>
<p>   </p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">juizes &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="st">&quot;Furto&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">60</span>, <span class="dv">80</span>), <span class="st">&quot;Tráfico&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">60</span>, <span class="dv">72</span>, <span class="dv">70</span>, <span class="dv">90</span>),</a>
<a class="sourceLine" id="cb1-2" title="2">                     <span class="dt">nome=</span><span class="kw">c</span>(<span class="st">&quot;Juiz 1&quot;</span>, <span class="st">&quot;Juiz 2&quot;</span>, <span class="st">&quot;Juiz 3&quot;</span>, <span class="st">&quot;Juiz 4&quot;</span>))</a>
<a class="sourceLine" id="cb1-3" title="3"></a>
<a class="sourceLine" id="cb1-4" title="4"><span class="kw">ggplot</span>(juizes, <span class="kw">aes</span>(<span class="dt">x=</span>Furto, <span class="dt">y=</span>Tráfico))<span class="op">+</span></a>
<a class="sourceLine" id="cb1-5" title="5"><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label=</span>nome))<span class="op">+</span></a>
<a class="sourceLine" id="cb1-6" title="6"><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb1-7" title="7"><span class="st">  </span><span class="kw">theme_classic</span>()</a></code></pre></div>
<p><img src="index_files/figure-revealjs/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
</section><section id="estrategia-adotada---exemplo-1" class="slide level2">
<h2>Estratégia adotada - exemplo</h2>
<p>   </p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">a &lt;-<span class="st"> </span><span class="kw">dist</span>(juizes[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">method=</span><span class="st">&quot;euclidean&quot;</span>)</a>
<a class="sourceLine" id="cb2-2" title="2"><span class="kw">as.matrix</span>(a)</a></code></pre></div>
<pre><code>##          1        2        3        4
## 1  0.00000 15.62050 31.62278 58.30952
## 2 15.62050  0.00000 20.09975 43.86342
## 3 31.62278 20.09975  0.00000 28.28427
## 4 58.30952 43.86342 28.28427  0.00000</code></pre>
<p>   </p>
<p>Neste exemplo, o Juiz 1 seria o âncora. Logo, os pontos ideais dos juízes 1, 2 3 e 4 seriam, respectivamente: 0, 15, 31 e 58.</p>
</section></section>
<section><section id="testando-a-hipotese" class="title-slide slide level1"><h1>Testando a hipótese</h1></section><section id="resultados" class="slide level2">
<h2>Resultados</h2>
<p>   </p>
<p>O método proposto no capítulo anterior se baseia em dois parâmetros: 1) quantos (e quais) crimes serão utilizados para medir as preferências; 2) número mínimo de decisões proferidas por cada juiz em cada crime. Quanto maior forem ambos os parâmetros, mais preciso será o método</p>
<p>   </p>
<p>No entanto, os Juízes de 1º Grau, como já dito, nem sempre julgam todos os tipos de crime, de modo que aumentar a quantidade de crimes utilizados para medir as preferências, reduz a amostra de Juízes. O mesmo ocorre se aumentarmos o número mínimo de decisões por Juiz em cada crime. Às vezes, um Juiz até chega a proferir decisões em vários crimes, mas nem sempre em grande quantidade.</p>
<p>   </p>
<p>Ou seja, o método desenvolvido apresenta um trade-off entre precisão e tamanho da amostra. Quanto mais preciso (maior o número de crimes e do número mínimo de decisões proferidas por cada Juiz em cada crime), menor será a amostra disponível de Juízes, prejudicando o teste da hipótese.</p>
</section><section id="resultados-1" class="slide level2">
<h2>Resultados</h2>
<p>   </p>
<p>A estratégia adotada foi a de testar a hipótese a partir de algumas combinações dos parâmetros, sempre mantendo uma amostra final superior a 30 Juízes, quais sejam: 1) Furto e Roubo com, no mínimo, 100 decisões por crime; 2) Furto, Roubo e Receptação com, no mínimo, 50 decisões por crime; 3) Furto, Roubo, Receptação e Tráfico com, no mínimo, 30 decisões por crime.</p>
<p>   </p>
<p>Outras combinações podem ser testadas através do <a href="https://lucasufmg.shinyapps.io/shiny/">Dashboard</a> ou fazendo o download da base de dados e dos códigos no endereço: <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TCYTEO" class="uri">https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TCYTEO</a></p>
</section><section id="resultados---1-combinacao" class="slide level2">
<h2>Resultados - 1ª Combinação</h2>
<p>   </p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Estimate
</th>
<th style="text-align:left;">
Std. Error
</th>
<th style="text-align:left;">
Razão de chances
</th>
<th style="text-align:left;">
Intervalo
</th>
<th style="text-align:left;">
Pr(&gt;|z|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercepto
</td>
<td style="text-align:left;">
0.233
</td>
<td style="text-align:left;">
0.747
</td>
<td style="text-align:left;">
1.262
</td>
<td style="text-align:left;">
0.292 , 5.455
</td>
<td style="text-align:left;">
0.755
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência
</td>
<td style="text-align:left;">
0.037
</td>
<td style="text-align:left;">
0.001
</td>
<td style="text-align:left;">
1.038
</td>
<td style="text-align:left;">
1.035 , 1.041
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
IDHM
</td>
<td style="text-align:left;">
-2.323
</td>
<td style="text-align:left;">
0.769
</td>
<td style="text-align:left;">
0.098
</td>
<td style="text-align:left;">
0.022 , 0.442
</td>
<td style="text-align:left;">
0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
Taxa de Homicídio
</td>
<td style="text-align:left;">
-0.019
</td>
<td style="text-align:left;">
0.003
</td>
<td style="text-align:left;">
0.982
</td>
<td style="text-align:left;">
0.976 , 0.988
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância inicial -Ref: Entrância Final
</td>
<td style="text-align:left;">
0.69
</td>
<td style="text-align:left;">
0.538
</td>
<td style="text-align:left;">
1.994
</td>
<td style="text-align:left;">
0.695 , 5.719
</td>
<td style="text-align:left;">
0.199
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância intermediária -Ref: Entrância Final
</td>
<td style="text-align:left;">
0.615
</td>
<td style="text-align:left;">
0.146
</td>
<td style="text-align:left;">
1.85
</td>
<td style="text-align:left;">
1.39 , 2.462
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Inicial
</td>
<td style="text-align:left;">
-0.005
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.995
</td>
<td style="text-align:left;">
0.976 , 1.015
</td>
<td style="text-align:left;">
0.622
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Intermediária
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.003
</td>
<td style="text-align:left;">
0.99
</td>
<td style="text-align:left;">
0.985 , 0.995
</td>
<td style="text-align:left;">
0
</td>
</tr>
</tbody>
</table>
</section><section id="resultados---2-combinacao" class="slide level2">
<h2>Resultados - 2ª Combinação</h2>
<p>   </p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Estimate
</th>
<th style="text-align:left;">
Std. Error
</th>
<th style="text-align:left;">
Razão de chances
</th>
<th style="text-align:left;">
Intervalo
</th>
<th style="text-align:left;">
Pr(&gt;|z|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercepto
</td>
<td style="text-align:left;">
-2.4
</td>
<td style="text-align:left;">
1.052
</td>
<td style="text-align:left;">
0.091
</td>
<td style="text-align:left;">
0.012 , 0.712
</td>
<td style="text-align:left;">
0.022
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência
</td>
<td style="text-align:left;">
0.038
</td>
<td style="text-align:left;">
0.002
</td>
<td style="text-align:left;">
1.039
</td>
<td style="text-align:left;">
1.036 , 1.042
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
IDHM
</td>
<td style="text-align:left;">
1.206
</td>
<td style="text-align:left;">
1.09
</td>
<td style="text-align:left;">
3.34
</td>
<td style="text-align:left;">
0.394 , 28.293
</td>
<td style="text-align:left;">
0.269
</td>
</tr>
<tr>
<td style="text-align:left;">
Taxa de Homicídio
</td>
<td style="text-align:left;">
-0.024
</td>
<td style="text-align:left;">
0.005
</td>
<td style="text-align:left;">
0.976
</td>
<td style="text-align:left;">
0.966 , 0.986
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância inicial -Ref: Entrância Final
</td>
<td style="text-align:left;">
0.335
</td>
<td style="text-align:left;">
0.893
</td>
<td style="text-align:left;">
1.397
</td>
<td style="text-align:left;">
0.243 , 8.038
</td>
<td style="text-align:left;">
0.708
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância intermediária -Ref: Entrância Final
</td>
<td style="text-align:left;">
-0.364
</td>
<td style="text-align:left;">
0.187
</td>
<td style="text-align:left;">
0.695
</td>
<td style="text-align:left;">
0.481 , 1.003
</td>
<td style="text-align:left;">
0.052
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Inicial
</td>
<td style="text-align:left;">
-0.001
</td>
<td style="text-align:left;">
0.017
</td>
<td style="text-align:left;">
0.999
</td>
<td style="text-align:left;">
0.966 , 1.034
</td>
<td style="text-align:left;">
0.96
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Intermediária
</td>
<td style="text-align:left;">
0.013
</td>
<td style="text-align:left;">
0.004
</td>
<td style="text-align:left;">
1.013
</td>
<td style="text-align:left;">
1.004 , 1.021
</td>
<td style="text-align:left;">
0.004
</td>
</tr>
</tbody>
</table>
</section><section id="resultados---3-combinacao" class="slide level2">
<h2>Resultados - 3ª Combinação</h2>
<p>   </p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Estimate
</th>
<th style="text-align:left;">
Std. Error
</th>
<th style="text-align:left;">
Razão de chances
</th>
<th style="text-align:left;">
Intervalo
</th>
<th style="text-align:left;">
Pr(&gt;|z|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercepto
</td>
<td style="text-align:left;">
-1.922
</td>
<td style="text-align:left;">
1.262
</td>
<td style="text-align:left;">
0.146
</td>
<td style="text-align:left;">
0.012 , 1.736
</td>
<td style="text-align:left;">
0.128
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência
</td>
<td style="text-align:left;">
0.026
</td>
<td style="text-align:left;">
0.002
</td>
<td style="text-align:left;">
1.026
</td>
<td style="text-align:left;">
1.023 , 1.03
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
IDHM
</td>
<td style="text-align:left;">
0.155
</td>
<td style="text-align:left;">
1.331
</td>
<td style="text-align:left;">
1.167
</td>
<td style="text-align:left;">
0.086 , 15.87
</td>
<td style="text-align:left;">
0.907
</td>
</tr>
<tr>
<td style="text-align:left;">
Taxa de Homicídio
</td>
<td style="text-align:left;">
-0.006
</td>
<td style="text-align:left;">
0.005
</td>
<td style="text-align:left;">
0.994
</td>
<td style="text-align:left;">
0.985 , 1.003
</td>
<td style="text-align:left;">
0.205
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância inicial -Ref: Entrância Final
</td>
<td style="text-align:left;">
1.459
</td>
<td style="text-align:left;">
0.927
</td>
<td style="text-align:left;">
4.303
</td>
<td style="text-align:left;">
0.699 , 26.484
</td>
<td style="text-align:left;">
0.116
</td>
</tr>
<tr>
<td style="text-align:left;">
Entrância intermediária -Ref: Entrância Final
</td>
<td style="text-align:left;">
-0.753
</td>
<td style="text-align:left;">
0.255
</td>
<td style="text-align:left;">
0.471
</td>
<td style="text-align:left;">
0.286 , 0.776
</td>
<td style="text-align:left;">
0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Inicial
</td>
<td style="text-align:left;">
-0.016
</td>
<td style="text-align:left;">
0.017
</td>
<td style="text-align:left;">
0.984
</td>
<td style="text-align:left;">
0.953 , 1.017
</td>
<td style="text-align:left;">
0.339
</td>
</tr>
<tr>
<td style="text-align:left;">
Preferência: Entrância Intermediária
</td>
<td style="text-align:left;">
0.019
</td>
<td style="text-align:left;">
0.005
</td>
<td style="text-align:left;">
1.019
</td>
<td style="text-align:left;">
1.01 , 1.028
</td>
<td style="text-align:left;">
0
</td>
</tr>
</tbody>
</table>
</section><section id="resultados---interpretacao" class="slide level2">
<h2>Resultados - Interpretação</h2>
<p>   </p>
<p>A razão de chances da preferência política ficou nos três modelos entre 1.023 a 1.042. Isso significa que a cada aumento de uma unidade no ponto ideal (em direção a uma ideologia mais punitivista) há um aumento entre 2.3% a 4.2% de chance de o juiz proferir uma sentença condenatória, ao invés de uma absolutória.</p>
<p>   </p>
<p>Exemplificando, os Juízes que se situaram nos extremos ideológicos do último modelo (3ª Combinação) estavam a uma distância entre si de 71 unidades. A partir da razão de chances, podemos dizer que o Juiz mais punitivista tinha aproximadamente entre 2,63 a 4 vezes mais chances de proferir uma sentença condenatória do que o Juiz mais garantista da amostra.</p>
</section><section id="discussao" class="slide level2">
<h2>Discussão</h2>
<p>   </p>
<p><strong>Sentencing</strong>: Características dos juízes também importam</p>
<p>   </p>
<p><strong>Comportamento Judicial</strong>: Postulado da hierarquia?</p>
</section></section>
<section><section id="consideracoes-finais" class="title-slide slide level1"><h1>Considerações finais</h1></section><section id="conclusao" class="slide level2">
<h2>Conclusão</h2>
<p>   </p>
<p>Em termos simples, os achados empíricos desta dissertação indicam que juízes que possuem uma preferência política a favor de um recrudescimento das punições distribuídas pelo governo, aumento de penas e encarceramentos tenderão, mesmo diante das mesmas evidências, provas, leis, princípios e jurisprudências, a proferir sentenças condenatórias com maior frequência do que aqueles juízes que possuem preferências políticas opostas.</p>
<p>   </p>
<p>Exemplo: casos narrados na introdução sobre Furto</p>
</section><section id="pesquisas-futuras" class="slide level2">
<h2>Pesquisas Futuras</h2>
<p>   </p>
<p>1 - Mensuração das preferências políticas em uma dimensão fundamental (liberal-conservador)</p>
<p>   </p>
<p>2 - Construção de um desenho de pesquisa capaz de testar qual das duas teorias (Atitudinal e Estratégica) possui um maior poder explicativo</p>
<p>   </p>
<p>3 - Estimação do efeito das preferências políticas sobre o tamanho das penas</p>
<p>   </p>
<p>4 - Identificação dos vieses e heurísticas que afetam os Juízes de 1º Grau</p>
<p>   </p>
<p>5 - Mensuração das preferências de todos os juízes em uma escala comparável</p>
</section></section>
    </div>
  </div>

  <script src="index_files/reveal.js-3.3.0.1/lib/js/head.min.js"></script>
  <script src="index_files/reveal.js-3.3.0.1/js/reveal.js"></script>

  <script>

      // Full list of configuration options available at:
      // https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        // Push each slide change to the browser history
        history: true,
        // Vertical centering of slides
        center: false,
        // Transition style
        transition: 'slide', // none/fade/slide/convex/concave/zoom
        // Transition style for full page slide backgrounds
        backgroundTransition: 'slide', // none/fade/slide/convex/concave/zoom
        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: '100%',
        height: '100%',



        // Optional reveal.js plugins
        dependencies: [
          { src: 'index_files/reveal.js-3.3.0.1/plugin/search/search.js', async: true },
          { src: 'index_files/reveal.js-3.3.0.1/plugin/zoom-js/zoom.js', async: true },
        ]
      });
    </script>
  <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>

<script>
  (function() {
    if (window.jQuery) {
      Reveal.addEventListener( 'slidechanged', function(event) {  
        window.jQuery(event.previousSlide).trigger('hidden');
        window.jQuery(event.currentSlide).trigger('shown');
      });
    }
  })();
</script>


  </body>
</html>
